server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://chenyuejun.mysql.rds.aliyuncs.com/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: test
    password: test
  # zookeeper配置
  cloud:
    zookeeper:
      connect-string: 192.168.2.101:2181

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.snow.springboot.entities
   # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml







