server:
  port: 80

spring:
  application:
    name: cloud-order-cs-server
  # consul配置
  cloud:
    consul:
      host: 192.168.2.101
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        tags: version=1.0
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        healthCheckInterval: 15s
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
