server:
  port: 80

spring:
  application:
    name: cloud-order-hsytirx-server

eureka:
  instance:
    instance-id: order80 #管理界面显示服务ID
    prefer-ip-address: true #管理界面点服务ID显示IP地址
  client:
    # 表示是否将自己注册进Eureka 默认 true
    register-with-eureka: false
    # 是否从EurekaServer抓取已有的注册信息，默认true 单节点无所谓，
    # 集群必须设置为true才能配合ribbon使用负载均衡。
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka  # 单机版配置
      # 集群配置
      #defaultZone: http://eureka7002.com:7002/eureka, http://eureka7001.com:7001/eureka
# 设置 Feign的超时时间，默认是1秒 单位毫秒
ribbon:
  # 指定建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 8000
  # 指定建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 8000

logging:
  level:
    # 以什么日志级别监控哪个接口
    com.snow.springboot.service.PaymentFeignService: debug

#开启hystrix 服务保护
feign:
  hystrix:
    enabled: true
